spring:
  application:
    name: example-app
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
      formate-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

auth:
  requiredAuthPaths:
    - "/graphql/**"

  accessiblePaths:
    - "/login"
    - "/signup"
    - "/"
